esphome:
  name: toslink-switch
  friendly_name: Toslink Switch
  on_boot:
    priority: -100
    then:
    - button.press: selector
    - delay: 500ms
    - select.set_index:
        id: input
        index: 2

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password

ota:
  password: !secret password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Toslink-Switch Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

binary_sensor:
  - platform: gpio
    pin: 
      number: 33
      mode:
        input: True
        pulldown: True
      inverted: True
    id: input_blue
    on_press:
      - lambda: |-
          id(state) = 0;
          ESP_LOGD("input_led_status", "pin 33, blue"); 

output: 
  - platform: gpio
    pin:
      number: 26
      mode:
        output: True
    id: selector_gpio

button:
  - platform: output
    id: selector
    name: "selector test"
    output: selector_gpio
    duration: 400ms
    on_press:
      - lambda: |-
          id(state) += 1;
          ESP_LOGD("pressed_button", "incremented state");

globals:
  - id: state
    type: int

select:
  - platform: template
    id: input
    name: Toslink Input
    optimistic: True
    options:
      - TV
      - Other
      - PC
    on_value:
      - while: 
          condition:
            lambda: |-
              return id(state) != i;
          then:
            - button.press: selector
